import { TradingTimesResponse } from '@deriv/api-types';
import { TInitialChartData } from 'src/types';

export const MockActiveSymbol: TInitialChartData['activeSymbols'] = [
    {
        allow_forward_starting: 0,
        display_name: 'AUD Basket',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'basket_index',
        market_display_name: 'Basket Indices',
        pip: 0.001,
        submarket: 'forex_basket',
        submarket_display_name: 'Forex Basket',
        symbol: 'WLDAUD',
        symbol_type: 'forex_basket',
    },
    {
        allow_forward_starting: 1,
        display_name: 'AUD/CAD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxAUDCAD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'AUD/CHF',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxAUDCHF',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'AUD/JPY',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxAUDJPY',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'AUD/NZD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxAUDNZD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'AUD/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxAUDUSD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Australian Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'asia_oceania_OTC',
        submarket_display_name: 'Asia/Oceania',
        symbol: 'OTC_AS51',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Bear Market Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.0001,
        submarket: 'random_daily',
        submarket_display_name: 'Daily Reset Indices',
        symbol: 'RDBEAR',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Bull Market Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.0001,
        submarket: 'random_daily',
        submarket_display_name: 'Daily Reset Indices',
        symbol: 'RDBULL',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Dutch Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'europe_OTC',
        submarket_display_name: 'Europe',
        symbol: 'OTC_AEX',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 0,
        display_name: 'EUR Basket',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'basket_index',
        market_display_name: 'Basket Indices',
        pip: 0.001,
        submarket: 'forex_basket',
        submarket_display_name: 'Forex Basket',
        symbol: 'WLDEUR',
        symbol_type: 'forex_basket',
    },
    {
        allow_forward_starting: 1,
        display_name: 'EUR/AUD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxEURAUD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'EUR/CAD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxEURCAD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'EUR/CHF',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxEURCHF',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'EUR/GBP',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxEURGBP',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'EUR/JPY',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxEURJPY',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'EUR/NZD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxEURNZD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'EUR/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxEURUSD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Euro 50 Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'europe_OTC',
        submarket_display_name: 'Europe',
        symbol: 'OTC_SX5E',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'French Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'europe_OTC',
        submarket_display_name: 'Europe',
        symbol: 'OTC_FCHI',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 0,
        display_name: 'GBP Basket',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'basket_index',
        market_display_name: 'Basket Indices',
        pip: 0.001,
        submarket: 'forex_basket',
        submarket_display_name: 'Forex Basket',
        symbol: 'WLDGBP',
        symbol_type: 'forex_basket',
    },
    {
        allow_forward_starting: 1,
        display_name: 'GBP/AUD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxGBPAUD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'GBP/CAD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxGBPCAD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'GBP/CHF',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxGBPCHF',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'GBP/JPY',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxGBPJPY',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'GBP/NOK',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxGBPNOK',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'GBP/NZD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxGBPNZD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'GBP/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxGBPUSD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'German Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'europe_OTC',
        submarket_display_name: 'Europe',
        symbol: 'OTC_GDAXI',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Gold/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'commodities',
        market_display_name: 'Commodities',
        pip: 0.01,
        submarket: 'metals',
        submarket_display_name: 'Metals',
        symbol: 'frxXAUUSD',
        symbol_type: 'commodities',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Hong Kong Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'asia_oceania_OTC',
        submarket_display_name: 'Asia/Oceania',
        symbol: 'OTC_HSI',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Japanese Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'asia_oceania_OTC',
        submarket_display_name: 'Asia/Oceania',
        symbol: 'OTC_N225',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'NZD/JPY',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxNZDJPY',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'NZD/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxNZDUSD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Oil/USD',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'commodities',
        market_display_name: 'Commodities',
        pip: 0.01,
        submarket: 'energy',
        submarket_display_name: 'Energy',
        symbol: 'frxBROUSD',
        symbol_type: 'commodities',
    },
    {
        allow_forward_starting: 0,
        display_name: 'Palladium/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'commodities',
        market_display_name: 'Commodities',
        pip: 0.01,
        submarket: 'metals',
        submarket_display_name: 'Metals',
        symbol: 'frxXPDUSD',
        symbol_type: 'commodities',
    },
    {
        allow_forward_starting: 0,
        display_name: 'Platinum/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'commodities',
        market_display_name: 'Commodities',
        pip: 0.01,
        submarket: 'metals',
        submarket_display_name: 'Metals',
        symbol: 'frxXPTUSD',
        symbol_type: 'commodities',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Silver/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'commodities',
        market_display_name: 'Commodities',
        pip: 0.0001,
        submarket: 'metals',
        submarket_display_name: 'Metals',
        symbol: 'frxXAGUSD',
        symbol_type: 'commodities',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Swiss Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'europe_OTC',
        submarket_display_name: 'Europe',
        symbol: 'OTC_SSMI',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'UK Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'europe_OTC',
        submarket_display_name: 'Europe',
        symbol: 'OTC_FTSE',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'US Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'americas_OTC',
        submarket_display_name: 'Americas',
        symbol: 'OTC_SPC',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'US Tech Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'americas_OTC',
        submarket_display_name: 'Americas',
        symbol: 'OTC_NDX',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 0,
        display_name: 'USD Basket',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'basket_index',
        market_display_name: 'Basket Indices',
        pip: 0.001,
        submarket: 'forex_basket',
        submarket_display_name: 'Forex Basket',
        symbol: 'WLDUSD',
        symbol_type: 'forex_basket',
    },
    {
        allow_forward_starting: 1,
        display_name: 'USD/CAD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxUSDCAD',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'USD/CHF',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxUSDCHF',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'USD/JPY',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.001,
        submarket: 'major_pairs',
        submarket_display_name: 'Major Pairs',
        symbol: 'frxUSDJPY',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'USD/MXN',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.0001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxUSDMXN',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'USD/NOK',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxUSDNOK',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'USD/PLN',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.0001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxUSDPLN',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'USD/SEK',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'forex',
        market_display_name: 'Forex',
        pip: 0.00001,
        submarket: 'minor_pairs',
        submarket_display_name: 'Minor Pairs',
        symbol: 'frxUSDSEK',
        symbol_type: 'forex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 10 (1s) Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ10V',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 10 Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.001,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_10',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 25 (1s) Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ25V',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 25 Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.001,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_25',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 50 (1s) Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ50V',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 50 Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.0001,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_50',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 75 (1s) Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ75V',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 75 Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.0001,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_75',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 100 (1s) Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ100V',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Volatility 100 Index',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_100',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 1,
        display_name: 'Wall Street Index',
        exchange_is_open: 0,
        is_trading_suspended: 0,
        market: 'indices',
        market_display_name: 'Stock Indices',
        pip: 0.01,
        submarket: 'americas_OTC',
        submarket_display_name: 'Americas',
        symbol: 'OTC_DJI',
        symbol_type: 'stockindex',
    },
    {
        allow_forward_starting: 0,
        display_name: 'BTC/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'cryptocurrency',
        market_display_name: 'Cryptocurrencies',
        pip: 0.001,
        submarket: 'non_stable_coin',
        submarket_display_name: 'Cryptocurrencies',
        symbol: 'cryBTCUSD',
        symbol_type: 'cryptocurrency',
    },
    {
        allow_forward_starting: 0,
        display_name: 'ETH/USD',
        exchange_is_open: 1,
        is_trading_suspended: 0,
        market: 'cryptocurrency',
        market_display_name: 'Cryptocurrencies',
        pip: 0.00001,
        submarket: 'non_stable_coin',
        submarket_display_name: 'Cryptocurrencies',
        symbol: 'cryETHUSD',
        symbol_type: 'cryptocurrency',
    },
];

const trading_times: TradingTimesResponse['trading_times'] = {
    markets: [
        {
            name: 'Forex',
            submarkets: [
                {
                    name: 'Major Pairs',
                    symbols: [
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'AUD/JPY',
                            symbol: 'frxAUDJPY',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'AUD/USD',
                            symbol: 'frxAUDUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'EUR/AUD',
                            symbol: 'frxEURAUD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'EUR/CAD',
                            symbol: 'frxEURCAD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'EUR/CHF',
                            symbol: 'frxEURCHF',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'EUR/GBP',
                            symbol: 'frxEURGBP',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'EUR/JPY',
                            symbol: 'frxEURJPY',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'EUR/USD',
                            symbol: 'frxEURUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'GBP/AUD',
                            symbol: 'frxGBPAUD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'GBP/JPY',
                            symbol: 'frxGBPJPY',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'GBP/USD',
                            symbol: 'frxGBPUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'USD/CAD',
                            symbol: 'frxUSDCAD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'USD/CHF',
                            symbol: 'frxUSDCHF',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'USD/JPY',
                            symbol: 'frxUSDJPY',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
                {
                    name: 'Minor Pairs',
                    symbols: [
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'AUD/CAD',
                            symbol: 'frxAUDCAD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'AUD/CHF',
                            symbol: 'frxAUDCHF',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'AUD/NZD',
                            symbol: 'frxAUDNZD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'EUR/NZD',
                            symbol: 'frxEURNZD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'GBP/CAD',
                            symbol: 'frxGBPCAD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'GBP/CHF',
                            symbol: 'frxGBPCHF',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'GBP/NOK',
                            symbol: 'frxGBPNOK',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'GBP/NZD',
                            symbol: 'frxGBPNZD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'NZD/JPY',
                            symbol: 'frxNZDJPY',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'NZD/USD',
                            symbol: 'frxNZDUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'USD/MXN',
                            symbol: 'frxUSDMXN',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'USD/NOK',
                            symbol: 'frxUSDNOK',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'USD/PLN',
                            symbol: 'frxUSDPLN',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'USD/SEK',
                            symbol: 'frxUSDSEK',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
            ],
        },
        {
            name: 'Basket Indices',
            submarkets: [
                {
                    name: 'Forex Basket',
                    symbols: [
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'AUD Basket',
                            symbol: 'WLDAUD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'EUR Basket',
                            symbol: 'WLDEUR',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'GBP Basket',
                            symbol: 'WLDGBP',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'USD Basket',
                            symbol: 'WLDUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
                {
                    name: 'Commodities Basket',
                    symbols: [
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                            ],
                            name: 'Gold Basket',
                            symbol: 'WLDXAU',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
            ],
        },
        {
            name: 'Stock Indices',
            submarkets: [
                {
                    name: 'Asia/Oceania',
                    symbols: [
                        {
                            events: [
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2020-12-28', descrip: 'Boxing Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-01-26', descrip: 'Australia Day Holiday' },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                                { dates: '2021-04-26', descrip: 'Anzac Day (obs)' },
                                { dates: '2021-06-14', descrip: "Queen's Birthday Holiday" },
                            ],
                            name: 'Australian Index',
                            symbol: 'OTC_AS51',
                            times: {
                                close: ['05:30:00', '19:00:00'],
                                open: ['00:00:00', '06:30:00'],
                                settlement: '21:00:00',
                            },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-12-24, 2020-12-31', descrip: 'Closes early (at 04:00)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-02-12, 2021-02-15', descrip: 'Lunar New Year' },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                                { dates: '2021-04-06', descrip: 'Ching Ming Festival' },
                                { dates: '2021-05-19', descrip: "Buddha's Birthday" },
                                { dates: '2021-06-14', descrip: 'Tuen Ng Festival' },
                                { dates: '2021-07-01', descrip: 'Sar Establishment Day' },
                                { dates: '2021-09-22', descrip: 'Day After Mid-autumn Fest' },
                                { dates: '2021-10-01', descrip: 'National Day (obs)' },
                                { dates: '2021-10-14', descrip: 'Chung Yeung Festival' },
                            ],
                            name: 'Hong Kong Index',
                            symbol: 'OTC_HSI',
                            times: {
                                close: ['04:00:00', '08:00:00'],
                                open: ['01:30:00', '05:00:00'],
                                settlement: '10:00:00',
                            },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-11-23', descrip: 'Labor Thanksgiving Day' },
                                { dates: '2020-12-31', descrip: 'Market Holiday' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-01-11', descrip: 'Coming-of-age Day' },
                                { dates: '2021-02-11', descrip: 'National Foundation Day' },
                                { dates: '2021-02-23', descrip: "Emperor's Birthday" },
                                { dates: '2021-04-29', descrip: 'Showa Day' },
                                { dates: '2021-05-03', descrip: 'Constitution Day' },
                                { dates: '2021-05-04', descrip: 'Greenery Day' },
                                { dates: '2021-05-05', descrip: "Children's Day" },
                                { dates: '2021-07-19', descrip: 'Marine Day' },
                                { dates: '2021-08-11', descrip: 'Mountain Day' },
                                { dates: '2021-09-20', descrip: 'Respect-for-the-aged Day' },
                                { dates: '2021-09-23', descrip: 'Autumnal Equinox Day' },
                                { dates: '2021-10-11', descrip: 'Health-sports Day' },
                                { dates: '2021-11-03', descrip: 'Culture Day' },
                            ],
                            name: 'Japanese Index',
                            symbol: 'OTC_N225',
                            times: { close: ['20:00:00'], open: ['00:00:00'], settlement: '22:00:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
                {
                    name: 'Europe',
                    symbols: [
                        {
                            events: [
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                            ],
                            name: 'Dutch Index',
                            symbol: 'OTC_AEX',
                            times: { close: ['20:30:00'], open: ['07:00:00'], settlement: '22:30:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                            ],
                            name: 'Euro 50 Index',
                            symbol: 'OTC_SX5E',
                            times: { close: ['20:00:00'], open: ['07:00:00'], settlement: '22:00:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                            ],
                            name: 'French Index',
                            symbol: 'OTC_FCHI',
                            times: { close: ['20:30:00'], open: ['07:00:00'], settlement: '22:30:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-12-24', descrip: 'Christmas Eve' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2020-12-31', descrip: "New Year's Eve" },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                                { dates: '2021-05-24', descrip: 'Whit Monday' },
                            ],
                            name: 'German Index',
                            symbol: 'OTC_GDAXI',
                            times: { close: ['20:30:00'], open: ['07:00:00'], settlement: '22:30:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-12-24', descrip: 'Christmas Eve' },
                                { dates: '2020-12-25', descrip: 'Christmas' },
                                { dates: '2020-12-31', descrip: "New Year's Eve" },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                                { dates: '2021-05-13', descrip: 'Ascension Day' },
                                { dates: '2021-05-24', descrip: 'Whit Monday' },
                            ],
                            name: 'Swiss Index',
                            symbol: 'OTC_SSMI',
                            times: { close: ['17:00:00'], open: ['08:00:00'], settlement: '19:00:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2020-12-28', descrip: 'Boxing Day (obs)' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                                { dates: '2021-05-03', descrip: 'Early May Bank Holiday' },
                                { dates: '2021-05-31', descrip: 'Late May Bank Holiday' },
                                { dates: '2021-08-30', descrip: 'Summer Bank Holiday' },
                            ],
                            name: 'UK Index',
                            symbol: 'OTC_FTSE',
                            times: { close: ['21:00:00'], open: ['07:00:00'], settlement: '23:00:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
                {
                    name: 'Americas',
                    symbols: [
                        {
                            events: [
                                { dates: '2020-11-26', descrip: 'Thanksgiving' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-01-18', descrip: 'Martin L. King Day' },
                                { dates: '2021-02-15', descrip: "Presidents' Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-05-31', descrip: 'Memorial Day' },
                                { dates: '2021-07-05', descrip: 'Independence Day Obs' },
                                { dates: '2021-09-06', descrip: 'Labor Day' },
                            ],
                            name: 'US Index',
                            symbol: 'OTC_SPC',
                            times: { close: ['21:00:00'], open: ['07:00:00'], settlement: '23:00:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-11-26', descrip: 'Thanksgiving' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-01-18', descrip: 'Martin L. King Day' },
                                { dates: '2021-02-15', descrip: "Presidents' Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-05-31', descrip: 'Memorial Day' },
                                { dates: '2021-07-05', descrip: 'Independence Day Obs' },
                                { dates: '2021-09-06', descrip: 'Labor Day' },
                            ],
                            name: 'US Tech Index',
                            symbol: 'OTC_NDX',
                            times: { close: ['21:00:00'], open: ['07:00:00'], settlement: '23:00:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: '2020-11-26', descrip: 'Thanksgiving' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-01-18', descrip: 'Martin L. King Day' },
                                { dates: '2021-02-15', descrip: "Presidents' Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-05-31', descrip: 'Memorial Day' },
                                { dates: '2021-07-05', descrip: 'Independence Day Obs' },
                                { dates: '2021-09-06', descrip: 'Labor Day' },
                            ],
                            name: 'Wall Street Index',
                            symbol: 'OTC_DJI',
                            times: { close: ['21:00:00'], open: ['07:00:00'], settlement: '23:00:00' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
            ],
        },
        {
            name: 'Commodities',
            submarkets: [
                {
                    name: 'Metals',
                    symbols: [
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                {
                                    dates: '2020-11-26, 2021-01-18, 2021-02-15, 2021-05-31, 2021-07-05, 2021-09-06',
                                    descrip: 'Closes early (at 16:30)',
                                },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                            ],
                            name: 'Gold/USD',
                            symbol: 'frxXAUUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                {
                                    dates: '2020-11-26, 2021-01-18, 2021-02-15, 2021-05-31, 2021-07-05, 2021-09-06',
                                    descrip: 'Closes early (at 16:30)',
                                },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                            ],
                            name: 'Palladium/USD',
                            symbol: 'frxXPDUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                {
                                    dates: '2020-11-26, 2021-01-18, 2021-02-15, 2021-05-31, 2021-07-05, 2021-09-06',
                                    descrip: 'Closes early (at 16:30)',
                                },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                            ],
                            name: 'Platinum/USD',
                            symbol: 'frxXPTUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                        {
                            events: [
                                { dates: 'Fridays', descrip: 'Closes early (at 20:55)' },
                                {
                                    dates: '2020-11-26, 2021-01-18, 2021-02-15, 2021-05-31, 2021-07-05, 2021-09-06',
                                    descrip: 'Closes early (at 16:30)',
                                },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                            ],
                            name: 'Silver/USD',
                            symbol: 'frxXAGUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
                {
                    name: 'Energy',
                    symbols: [
                        {
                            events: [
                                { dates: '2020-12-24, 2020-12-31', descrip: 'Closes early (at 12:30)' },
                                { dates: '2020-12-25', descrip: 'Christmas Day' },
                                { dates: '2020-12-28', descrip: 'Boxing Day (obs)' },
                                { dates: '2021-01-01', descrip: "New Year's Day" },
                                { dates: '2021-04-02', descrip: 'Good Friday' },
                                { dates: '2021-04-05', descrip: 'Easter Monday' },
                                { dates: '2021-05-03', descrip: 'Early May Bank Holiday' },
                                { dates: '2021-05-31', descrip: 'Late May Bank Holiday' },
                                { dates: '2021-08-30', descrip: 'Summer Bank Holiday' },
                            ],
                            name: 'Oil/USD',
                            symbol: 'frxBROUSD',
                            times: { close: ['19:30:00'], open: ['08:15:00'], settlement: '23:59:59' },
                            trading_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                        },
                    ],
                },
            ],
        },
        {
            name: 'Synthetic Indices',
            submarkets: [
                {
                    name: 'Continuous Indices',
                    symbols: [
                        {
                            events: [],
                            name: 'Volatility 10 (1s) Index',
                            symbol: '1HZ10V',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 10 Index',
                            symbol: 'R_10',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 25 (1s) Index',
                            symbol: '1HZ25V',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 25 Index',
                            symbol: 'R_25',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 50 (1s) Index',
                            symbol: '1HZ50V',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 50 Index',
                            symbol: 'R_50',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 75 (1s) Index',
                            symbol: '1HZ75V',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 75 Index',
                            symbol: 'R_75',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 100 (1s) Index',
                            symbol: '1HZ100V',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 100 Index',
                            symbol: 'R_100',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 200 (1s) Index',
                            symbol: '1HZ200V',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Volatility 300 (1s) Index',
                            symbol: '1HZ300V',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                    ],
                },
                {
                    name: 'Daily Reset Indices',
                    symbols: [
                        {
                            events: [],
                            name: 'Bear Market Index',
                            symbol: 'RDBEAR',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'Bull Market Index',
                            symbol: 'RDBULL',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                    ],
                },
            ],
        },
        {
            name: 'Cryptocurrencies',
            submarkets: [
                {
                    name: 'Cryptocurrencies',
                    symbols: [
                        {
                            events: [],
                            name: 'BTC/USD',
                            symbol: 'cryBTCUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                        {
                            events: [],
                            name: 'ETH/USD',
                            symbol: 'cryETHUSD',
                            times: { close: ['23:59:59'], open: ['00:00:00'], settlement: '23:59:59' },
                            trading_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                        },
                    ],
                },
            ],
        },
    ],
};

export const MockTradingTime = {
    trading_times,
};

export function masterData() {
    const _date = new Date();
    _date.setMinutes(_date.getMinutes(), 0, 0);

    let price = 8350.41;
    price += parseFloat((price * 0.02 * Math.random() - price * 0.01).toFixed(2));
    const mock_items = [
        {
            Date: _date.toISOString().slice(0, 19),
            Close: price,
        },
    ];
    for (let i = 1; i < 10; i++) {
        const old_price = mock_items[mock_items.length - 1].Close;
        const change = old_price * 0.02 * Math.random() - old_price * 0.01; // random between +/-1% of current price
        const new_price = parseFloat(`${old_price + parseFloat(change.toFixed(2))}`).toFixed(4);
        _date.setMinutes(_date.getMinutes() - i * 2, 0, 0);
        const item = {
            Date: _date.toISOString().slice(0, 19),
            Open: parseFloat(new_price) - 10.5,
            High: parseFloat(new_price) + 15.5,
            Low: parseFloat(new_price) - 15,
            Close: parseFloat(new_price),
        };
        mock_items.push(item);
    }
    return mock_items;
}
