import BottomWidgetsContainerStore from '../store/BottomWidgetsContainerStore';
import TimeperiodStore from '../store/TimeperiodStore';
import ChartStore from '../store/ChartStore';
import ChartTypeStore from '../store/ChartTypeStore';
import ChartModeStore from '../store/ChartModeStore';
import StudyLegendStore from '../store/StudyLegendStore';
import DrawToolsStore from '../store/DrawToolsStore';
import ChartTitleStore from '../store/ChartTitleStore';
import ViewStore from '../store/ViewStore';
import CrosshairStore from '../store/CrosshairStore';
import ShareStore from '../store/ShareStore';
import ChartSettingStore from '../store/ChartSettingStore';
import LoaderStore from '../store/LoaderStore';
import FavoriteStore from '../store/FavoriteStore';
import ChartSizeStore from '../store/ChartSizeStore';
import RoutingStore from '../store/RoutingStore';
import CurrentSpotStore from '../store/CurrentSpotStore';
import ChartState from '../store/ChartState';
import Notifier from '../store/Notifier';
import LastDigitStatsStore from '../store/LastDigitStatsStore';
import NavigationWidgetStore from '../store/NavigationWidgetStore';
import HighestLowestStore from '../store/HighestLowestStore';
import PaginationLoaderStore from '../store/PaginationLoaderStore';
import ToolbarWidgetStore from '../store/ToolbarWidgetStore';
import ScrollStore from '../store/ScrollStore';

export type TMainStore = {
    notifier: Notifier;
    favorites: FavoriteStore;
    chart: ChartStore;
    state: ChartState;
    chartType: ChartTypeStore;
    chartMode: ChartModeStore;
    studies: StudyLegendStore;
    drawTools: DrawToolsStore;
    chartTitle: ChartTitleStore;
    timeperiod: TimeperiodStore;
    view: ViewStore;
    crosshair: CrosshairStore;
    share: ShareStore;
    chartSetting: ChartSettingStore;
    loader: LoaderStore;
    chartSize: ChartSizeStore;
    routing: RoutingStore;
    currentSpot: CurrentSpotStore;
    lastDigitStats: LastDigitStatsStore;
    bottomWidgetsContainer: BottomWidgetsContainerStore;
    navigationWidget: NavigationWidgetStore;
    highestLowest: HighestLowestStore;
    paginationLoader: PaginationLoaderStore;
    toolbarWidget: ToolbarWidgetStore;
    scroll: ScrollStore;
};

export type Stores = Notifier;
