
import {
    DrawToolsChannelIcon,
    DrawToolsContinuousIcon,
    DrawToolsFibonaccifanIcon,
    DrawToolsHorizontalIcon,
    DrawToolsLineIcon,
    DrawToolsRayIcon,
    DrawToolsRectangleIcon,
    DrawToolsTrendIcon,
    DrawToolsVerticalIcon,
    IndicatorCatMomentumIcon,
    IndicatorCatTrendLightIcon,
    IndicatorCatVolatilityIcon,
    IndicatorCatAveragesIcon,
    IndicatorCatOtherIcon,
    IndicatorAwesomeOscillatorIcon,
    IndicatorDTrendedIcon,
    IndicatorGatorIcon,
    IndicatorMacdIcon,
    IndicatorRateChangeIcon,
    IndicatorRSIIcon,
    IndicatorStochasticOscillatorIcon,
    IndicatorStochasticMomentumIcon,
    IndicatorWilliamPercentIcon,
    IndicatorAroonIcon,
    IndicatorAdxIcon,
    IndicatorCommodityChannelIndexIcon,
    IndicatorIchimokuIcon,
    IndicatorParabolicIcon,
    IndicatorZigZagIcon,
    IndicatorBollingerIcon,
    IndicatorDonchianIcon,
    IndicatorAveragesIcon,
    IndicatorEnvelopeIcon,
    IndicatorAlligatorIcon,
    IndicatorFractalChaosIcon,
    // Chart Types
    TypeAreaIcon,
    TypeCandleIcon,
    TypeHollowIcon,
    TypeOhlcIcon,
} from './components/Icons.jsx';

export const drawTools = {
    channel:    { id: 'channel',     text: t.translate('Channel'), icon: DrawToolsChannelIcon },
    segment:    { id: 'continuous',  text: t.translate('Continuous'), icon: DrawToolsContinuousIcon },
    fibfan:     { id: 'fibfan',      text: t.translate('Fib Fan'), icon: DrawToolsFibonaccifanIcon },
    horizontal: { id: 'horizontal',  text: t.translate('Horizontal'), icon: DrawToolsHorizontalIcon },
    line:       { id: 'line',        text: t.translate('Line'), icon: DrawToolsLineIcon },
    ray:        { id: 'ray',         text: t.translate('Ray'), icon: DrawToolsRayIcon },
    rectangle:  { id: 'rectangle',   text: t.translate('Rectangle'), icon: DrawToolsRectangleIcon },
    tirone:     { id: 'tirone',      text: t.translate('Trend'), icon: DrawToolsTrendIcon },
    vertical:   { id: 'vertical',    text: t.translate('Vertical'), icon: DrawToolsVerticalIcon },
};

export const IndicatorsTree = [
    {
        id: 'momentum',
        name: t.translate('Momentum'),
        icon: IndicatorCatMomentumIcon,
        items: [
            { id: 'Awesome', name: t.translate('Awesome Oscillator'), description: t.translate('There isn\'t any description here.'), icon: IndicatorAwesomeOscillatorIcon },
            { id: 'Detrended', name: t.translate('Detrended Price Oscillator'), description: t.translate('There isn\'t any description here.'), icon: IndicatorDTrendedIcon },
            { id: 'Gator', name: t.translate('Gator Oscillator'), description: t.translate('There isn\'t any description here.'), icon: IndicatorGatorIcon },
            { id: 'macd', name: t.translate('MACD'), description: t.translate('There isn\'t any description here.'), icon: IndicatorMacdIcon },
            { id: 'Price ROC', name: t.translate('Rate of Change'), description: t.translate('There isn\'t any description here.'), icon: IndicatorRateChangeIcon },
            { id: 'rsi', name: t.translate('Relative Strength Index (RSI)'), description: t.translate('There isn\'t any description here.'), icon: IndicatorRSIIcon },
            { id: 'stochastics', name: t.translate('Stochastic Oscillator'), description: t.translate('There isn\'t any description here.'), icon: IndicatorStochasticOscillatorIcon },
            { id: 'Stch Mtm', name: t.translate('Stochastic Momentum Index'), description: t.translate('There isn\'t any description here.'), icon: IndicatorStochasticMomentumIcon },
            { id: 'Williams %R', name: t.translate('William\'s Percent Range'), description: t.translate('There isn\'t any description here.'), icon: IndicatorWilliamPercentIcon },
        ],
    },
    {
        id: 'trend',
        name: t.translate('Trend'),
        icon: IndicatorCatTrendLightIcon,
        items: [
            { id: 'Aroon', name: t.translate('Aroon'), description: t.translate('There isn\'t any description here.'), icon: IndicatorAroonIcon },
            { id: 'ADX', name: t.translate('ADX/DMS'), description: t.translate('There isn\'t any description here.'), icon: IndicatorAdxIcon },
            { id: 'CCI', name: t.translate('Commodity Channel Index'), description: t.translate('There isn\'t any description here.'), icon: IndicatorCommodityChannelIndexIcon },
            { id: 'Ichimoku Clouds', name: t.translate('Ichimoku Clouds'), description: t.translate('There isn\'t any description here.'), icon: IndicatorIchimokuIcon },
            { id: 'PSAR', name: t.translate('Parabolic SAR'), description: t.translate('There isn\'t any description here.'), icon:  IndicatorParabolicIcon },
            { id: 'ZigZag', name: t.translate('Zig Zag'), description: t.translate('There isn\'t any description here.'), icon: IndicatorZigZagIcon },
        ],
    },
    {
        id: 'volatility',
        name: t.translate('Volatility'),
        icon: IndicatorCatVolatilityIcon,
        items: [
            { id: 'Bollinger Bands', name: t.translate('Bollinger Bands'), description: t.translate('There isn\'t any description here.'), icon: IndicatorBollingerIcon },
            { id: 'Donchian Channel', name: t.translate('Donchian Channel'), description: t.translate('There isn\'t any description here.'), icon: IndicatorDonchianIcon },
        ],
    },
    {
        id: 'moving-averages',
        name: t.translate('Moving averages'),
        icon: IndicatorCatAveragesIcon,
        items: [
            { id: 'ma', name: t.translate('Moving Average (MA)'), description: t.translate('There isn\'t any description here.'), icon: IndicatorAveragesIcon },
            { id: 'MA Env', name: t.translate('Moving Average Envelope'), description: t.translate('There isn\'t any description here.'), icon: IndicatorEnvelopeIcon },
        ],
    },
    {
        id: 'others',
        name: t.translate('Others'),
        icon: IndicatorCatOtherIcon,
        items: [
            { id: 'Alligator', name: t.translate('Alligator'), description: t.translate('There isn\'t any description here.'), icon: IndicatorAlligatorIcon },
            { id: 'Fractal Chaos Bands', name: t.translate('Fractal Chaos Band'), description: t.translate('There isn\'t any description here.'), icon: IndicatorFractalChaosIcon },
        ],
    },
];

export const ExcludedStudies = {
    Beta: true,
    // volume is not supported in chart
    Klinger: true,
    'Trade Vol': true,
    'Vol ROC': true,
    'Price Vol': true,
    'Pos Vol': true,
    'Neg Vol': true,
    'On Bal Vol': true,
    'Vol Osc': true,
    volume: true,
    'vol undr': true,
    'vol profile': true,
    'W MFI': true,
    EOM: true,
    'Chaikin MF': true,
    Twiggs: true,
    // end volume
    'Aroon Osc': true,
    'Lin R2': true,
    'Lin Fcst': true,
    'Lin Incpt': true,
    'Time Fcst': true,
    'VT Filter': true,
    TRIX: true,
    'STD Dev': true,
    Swing: true,
    'Acc Swing': true,
    'Price ROC': true,
    Momentum: true,
    'Hist Vol': true,
    'Pretty Good': true,
    Ultimate: true,
    'Chaikin Vol': true,
    'Price Osc': true,
    'True Range': true,
    ATR: true,
    'Ehler Fisher': true,
    Schaff: true,
    QStick: true,
    Coppock: true,
    'Chande Mtm': true,
    'Chande Fcst': true,
    'Intraday Mtm': true,
    RAVI: true,
    'Random Walk': true,
    'High Low': true,
    'High-Low': true,
    'Med Price': true,
    'Fractal Chaos': true,
    GAPO: true,
    'Prime Number Bands': true,
    'Prime Number': true,
    HHV: true,
    LLV: true,
    'Mass Idx': true,
    Keltner: true,
    'Elder Ray': true,
    'Elder Force': true,
    'LR Slope': true,
    COG: true,
    'Typical Price': true,
    'Weighted Close': true,
    'M Flow': true,
    'W Acc Dist': true,
    'val lines': true,
    correl: true,
    PMO: true,
    'Rel Vol': true,
    'ATR Bands': true,
    'STARC Bands': true,
    'ATR Trailing Stop': true,
    'Boll BW': true,
    'Boll %b': true,
    'Rel Vig': true,
    'Elder Impulse': true,
    'Pivot Points': true,
    VWAP: true,
    AVWAP: true,
    'P Rel': true,
    'Perf Idx': true,
    Ulcer: true,
    'Bal Pwr': true,
    'Trend Int': true,
    Choppiness: true,
    Disparity: true,
    'Rainbow MA': true,
    'Rainbow Osc': true,
    'Pring KST': true,
    'Pring Sp-K': true,
    Darvas: true,
    Supertrend: true,
    Vortex: true,
    PSY: true,
    'MA Dev': true,
    Shinohara: true,
    'VT HZ Filter': true,
};

export const ChartTypes = [
    { id: 'mountain',      text: t.translate('Area'),   candleOnly: false, icon: TypeAreaIcon   },
    { id: 'candle',        text: t.translate('Candle'), candleOnly: true,  icon: TypeCandleIcon },
    { id: 'hollow_candle', text: t.translate('Hollow'), candleOnly: true,  icon: TypeHollowIcon },
    { id: 'colored_bar',   text: t.translate('OHLC'),   candleOnly: true,  icon: TypeOhlcIcon   },
];

export const Intervals = [
    {
        key: 'tick',
        single: t.translate('tick'),
        items: [
            {
                interval: 0,
                num: 1,
            },
        ],
    }, {
        key: 'minute',
        single: t.translate('minute'),
        plural: t.translate('minutes'),
        items: [
            { interval: 60, num: 1 },
            { interval: 120, num: 2 },
            { interval: 180, num: 3 },
            { interval: 300, num: 5 },
            { interval: 600, num: 10 },
            { interval: 900, num: 15 },
            { interval: 1800, num: 30 },
        ],
    }, {
        key: 'hour',
        single: t.translate('hour'),
        plural: t.translate('hours'),
        items: [
            { interval: 3600, num: 1 },
            { interval: 7200, num: 2 },
            { interval: 14400, num: 4 },
            { interval: 28800, num: 8 },
        ],
    }, {
        key: 'day',
        single: t.translate('day'),
        plural: t.translate('days'),
        items: [
            { interval: 86400, num: 1 },
        ],
    },
];
